---
name: Task - Linters

on:
  workflow_dispatch:
  workflow_call:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run prettier
        run: npx prettier --check .

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint root markdown
        uses: avto-dev/markdown-lint@v1
        with:
          config: "./.markdownlint.json"
          args: "."
          ignore: "./target"
      - name: Lint orchestrator markdown
        uses: avto-dev/markdown-lint@v1
        with:
          config: "../.markdownlint.json"

  toml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Download taplo
        run: |
          curl -L https://github.com/tamasfe/taplo/releases/download/0.9.3/taplo-linux-x86_64.gz -o taplo.gz
          gunzip taplo.gz
          chmod +x taplo
          mv taplo /usr/local/bin/taplo
      - uses: actions/checkout@v4
      - name: Check root toml files
        run: taplo fmt --config ./taplo/taplo.toml --check
      - name: Check orchestrator toml files
        working-directory: orchestrator
        run: taplo fmt --config ../taplo/taplo.toml --check
